name: Deploy GitHub Pages

on:
  push:
    branches:
      - gh-pages  # The branch where your `dist` content is located

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Specify the gh-pages branch for deployment
          publish_dir: .  # The content of the current branch's root directory
